# Generated by Django 3.0.8 on 2021-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Коротний опис'),
            preserve_default=False,
        ),
    ]
