# Generated by Django 3.0.8 on 2021-05-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_product_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(max_length=128, verbose_name='Коротний опис'),
        ),
    ]
