# Generated by Django 3.0.8 on 2021-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210504_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(blank=True, verbose_name='Коротний опис'),
        ),
    ]
